version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: lppm-press-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lppm
      POSTGRES_PASSWORD: lppm_secret
      POSTGRES_DB: lppm_press
    ports:
      - "5433:5432"
    volumes:
      - lppm_pgdata:/var/lib/postgresql/data
volumes:
  lppm_pgdata:
